### ISSUE TITLE
export ILogger interface

### ISSUE THREAD

**Issue by bc3** [jonnyreeves/js-logger#66]
Hello,

we are using your component and find it a very handy component. But we use VueJS in combination of typescript. And it is a petty that you do not export the ILogger interface in your logger.d.ts

Now we use a any object, and it would be nice to have the ilogger interface available for better typescript.

Thanks

**Comment by timm-gs** [comment]
I saw #68 and would propose to export all interface, since `ILogger` embeds/references them. 

In our app I had to re-export for example `IContext` and `ILoggerOpts` to make our extended logging package configurable with the `js-logger` types (in order to not create mapping types, which would also be a solution in this case).

**Comment by jonnyreeves** [comment]
Fixed in #82
